name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./api
          tags: c3controls/2ec-api:${{ github.sha }}, c3controls/2ec-api:latest

      - name: Deploy to DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy API
        run: doctl apps create-deployment 17962c1a-83bc-4157-8c20-fbb29aa5e869 --force-rebuild=true